Basic user interaction
Morrism1/tic-tac-toe pull request #2
Opened 2020-05-28 10:15 UTC by tacodtripe

In this branch, we create a mock flow from a tic-tac-toe game to inspect the logic involved in the game.

2020-05-28 12:18 UTC, stratospherique requested changes
### Great work @team :clap: :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

#### Behavior 
* [ ] In this step, not everything must work, the point is to make sure that you thought about everything listed below. You might do it only with inline comments. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [ ] `[REQUIRED]` game asks the player to select from available moves
  * [x] `[REQUIRED]` game informs player if the selected move is invalid
  * [ ] `[REQUIRED]` game displays board after the player move
  * [x] `[REQUIRED]` game informs player if the selected move is a winning move
  * [x] `[REQUIRED]` game informs player if the selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for the next player's move

##### Implementation details

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside the loop, all actions above should be repeated for each player separately (i,e one player turn per iteration).
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true
# initial instructions for player
current_player = player_one

while game_on
  # loop for each move
  # actions mentioned in the behaviour list above
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  else
  # switch current player
  end
end
```

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-05-29 10:12 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: :clap: , however, small changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your project.

### That's it :relieved: When finished, kindly submit a code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-05-29 10:12 UTC, stratospherique commented on bin/main
> +player_2 = gets.chomp # rubocop:todo Naming/VariableNumber
- Adding these rubocop rules could have been avoided if you name the player variable as 'player_one'. :pray:  remove these rules

2020-05-29 10:12 UTC, stratospherique commented on bin/main
> +current_player = 1
- current_player is supposed to host the instance of the current player(Object), not an number :mag:

2020-05-29 10:12 UTC, stratospherique commented on bin/main
> +puts "\nCongrats #{player_2} you won!"
- The part is supposed to be removed because it was replaced by the loop above.

2020-06-01 09:40 UTC, mikenath223 requested changes
### Hi Team 👋

You've obviously both done well on this.🚀
Let's make the following changes to make it better.

- [ ] Somewhere within the loop you should terminate the game when there is a winner/loser/tie. Kindly add a condition that ends the game based on these conditions.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-06-01 12:13 UTC, lekegitrepo commented
### Hi @tacodtripe and @Morrism1 :clap: :clap:
#### Good so far. Some requirements are not well implemented, check my comment below :point_down:

**_1. The game did not check for an invalid move_** :point_down: 
![Screenshot from 2020-06-01 05-55-40](https://user-images.githubusercontent.com/48312803/83407066-961bfe80-a3d5-11ea-8cae-f2f37e0f446d.png)

**_2. After two rounds the game terminals and declares a winner_**
**_which means the full implementation of these requirements :point_down:  are missing:_**
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move

**_3. The board did not display after the player move_**

**_fix these and submit for review_**

### Reviewed by Temitayo Adeleke.

2020-06-01 12:14 UTC, lekegitrepo requested changes
#### Status: Request changes

2020-06-02 10:05 UTC, mikenath223 requested changes
### Hello again Team 👋

Great job working with previous reviews, we are just a step away, hang in there.💪🚀

- [ ] Let's make this addition, we want the player to see the board before and after each move. Would you agree that helps the player know which board positions are filled? However, you can consider using an inline comment to show this message in the game loop.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-06-02 10:51 UTC, mikenath223 approved these changes
### CONGRATULATIONS  TEAM 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-06-02 10:54 UTC, merged